/*
 * DO NOT EDIT THIS FILE! 
 *
 * https://github.com/phillipalexander/aka
 *
 * Copyright (c) 2014 Phillip Alexander
 * Licensed under the MIT license.
 *
 */


'use strict';

var attributes = [
  // Environ
  'desert', 'tundra', 'mountain', 'space', 'field', 'urban', 'suburban', 'rural', 'alpine', 'savannah', 'tropical', 'chapparal',
  // Stealth and cunning
  'hidden', 'covert', 'uncanny', 'scheming', 'decisive', 'incredulous', 'stealth', 'underground', 'clandestine',
  // Personality
  'charistmatic', 'gregarious', 'optomistic', 'charming', 'clever', 'adorable', 'affable', 'convival', 'boisterous', 'jolly', 'hilarious', 'altruistic', 'ticklish', 'effervescent',
  // Volitility
  'unstable', 'dangerous', 'explosive', 'threatening', 'warring', 'persnickety', 'toxic', 'litigious', 'petulant', 'capricious', 'temperamental',
  // Needs correction
  'bad', 'evil', 'vestigial', 'unknown', 'unexpected', 'waning', 'incorrigible', 'terrible',
  // Organic Gems and materials
  'amber', 'coral', 'ivory', 'jet', 'nacre', 'pearl', 'obsidian', 'glass',
  // Regular Gems
  'agate', 'diamond', 'opal', 'ruby', 'onyx', 'sapphire', 'emerald', 'jade',
  // Chemistry
  'organic', 'metalic', 'cobalt', 'silver', 'golden', 'carbonic', 'iron', 'noble', 'radioactive',
  // Colors
  'chartreuse', 'mauve', 'incarnadine', 'periwinkle', 'viridescent', 'cerulean', 'erythraean', 'mazarine', 'vermilion',
];

var objects = [
  // Large cats
  'panther', 'wildcat', 'tiger', 'lion', 'cheetah', 'cougar', 'leopard',
  // Dinosaurs
  'triceratops', 'apatosaurus', 'stegosaurus', 'pterodactyl', 'ankylosaurus', 'iguanodon', 'velociraptor',
  // Reptiles and Amphibians
  'viper', 'python', 'boa', 'sidewinder', 'cobra', 'tortoise', 'salamander',
  // Other predators
  'grizzly', 'jackal', 'falcon', 'raptor',
  // Prey
  'wildebeest', 'gazelle', 'zebra', 'elk', 'moose', 'deer', 'ferret', 'marmot', 'echidna',
  // HORSES!
  'horse', 'stallion', 'foal', 'colt', 'mare', 'yearling', 'filly', 'gelding', 'stag', 'pony',
  // Occupations
  'nomad', 'cleric', 'pilot', 'vagabond', 'botantist', 'ballerina', 'farmer', 'orthodontist', 'house-sitter',
  // Technology
  'mainframe', 'device', 'motherboard', 'network', 'transistor', 'packet', 'robot', 'android', 'cyborg', 'datum',
  // Sea life
  'octopus', 'lobster', 'crab', 'barnacle', 'hammerhead', 'orca', 'piranha', 'jellyfish', 'starfish', 'seahorse',
  // Weather
  'storm', 'thunder', 'lightning', 'rain', 'hail', 'sun', 'drought', 'snow', 'monsoon', 'blizzard',
  // Other
  'warning', 'presence', 'weapon', 'juror', 'octogenarian',
  // Space
  'asteroid', 'satellite', 'moon', 'planet', 'star', 'nebula', 'cluster', 'blackhole', 'wormhole', 'quasar', 'cosmonaut',
  // Food
  'pizza', 'muffin', 'profiterole', 'cabbage', 'nectarine', 'meatloaf', 'cornucopia', 'sandwich', 'pancake', 'waffle', 'pumpkin',
  // Birds
  'jackdaw', 'bobolink', 'starling', 'chickadee', 'raven', 'hawk', 'kestrel', 'hummingbird', 'ibis', 'junco', 'lark', 'magpie', 'osprey', 'avocet', 'ptarmigan',
  // Plants
  'orchid', 'heliotrope', 'hyacinth', 'geranium', 'aeonium', 'graptopetalum', 'peony', 'lupine', 'ocotillo',
  // Social Dances
  'foxtrot', 'quadrille', 'tango', 'allemande', 'disco', 'merengue',
  // Conveyances
  'dirigible', 'motocycle', 'limosuine', 'tugboat', 'sailboat', 'frigate', 'submarine', 'scooter',
  // Fantasy Animals
  'centaur', 'unicorn', 'pheonix', 'mermaid', 'pegasus', 'troll', 'dragon', 'pixie', 'goblin', 'sphinx', 'hydra', 'gnome', 'house-elf', 'acromantula', 'chimaera', 'hippogriff',
];

var aka = {
  createName: function createCodename() {
    var randomAttribute = attributes[Math.floor(Math.random() * attributes.length)];
    var randomObject = objects[Math.floor(Math.random() * objects.length)];
    return randomAttribute + '-' + randomObject;
  }
};

module.exports = aka;
